# InstantVoidKill Settings

world_settings:
  world:
    void_y_level: 0

teleport_instead_of_kill: false
teleport_message: "You were teleported to safety!"
spawn_location:
  x: 0
  y: 100
  z: 0
  world: "world"
